import Head from "next/head";
import CaseBanner from "../../components/casestudy/CaseBanner";
import CaseStudies from "../../components/casestudy/CaseStudies";

function casestudy() {
    return ( 

        <>
        <Head>
        <title>Technology 1 || Casestudy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CaseBanner/>
      <CaseStudies/>
        </>
        
     );
}

export default casestudy;