import Head from "next/head";
import Contact from '../components/common/Contact';
import FAQ from "../components/common/FAQ";
import FaqBanner from "../components/faq/FaqBanner";


function Faq() {
    return ( 

        <>
        <Head>
        <title>Technology 1 || FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <FaqBanner/>
      <FAQ/>
      <Contact/>
        </>
     );
}

export default Faq;