import Head from 'next/head';
import Contact from '../components/common/Contact';
import FAQ from '../components/common/FAQ';
import Banner from '../components/home/Banner';
import Comments from '../components/home/Comments';
import Companies from '../components/home/Companies';
import Features from '../components/home/Features.';
import Goals from '../components/home/Goals';
import Portfolio from '../components/home/Portfolio';
import WorkProcess from '../components/home/WorkProcess';


export default function Home() {
  return (
    <>
      <Head>
        <title>Technology 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Banner/>
    <Companies/>
   <WorkProcess/>
   <Goals/>
   <Features/>
   <Portfolio/>
   <Comments/>
   <FAQ/>
   <Contact/>


    </>
  )
}
