import Head from "next/head";
import Comments from "../components/home/Comments";
import WorkProcess from "../components/home/WorkProcess";
import HowWeWork from "../components/service/HowWeWork";
import PriceSection from "../components/service/PriceSection";
import ServiceBanner from "../components/service/ServiceBanner";

function Service () {
    return ( 

        <>
        <Head>
        <title>Technology 1 || Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <ServiceBanner/>
        <HowWeWork/>
        <WorkProcess/>
        <Comments/>
        <PriceSection/>

        </>
     );
}

export default Service ;