import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Comments from "../components/home/Comments";
import HowWeWork from "../components/service/HowWeWork";
import SimpleNav from "../components/solutions/SimpleNav";
import SolutionBanner from "../components/solutions/SolutionBanner";
import SolutionGoal from "../components/solutions/SolutionGoal";

function Solutions() {
  const router = useRouter();

  useEffect(() => {
    window.addEventListener("scroll", function () {
      var crossed_div = this.document.querySelector(".solution_banner");
      var nav = document.querySelector(".simple_nav");
if(nav){

    var main_nav = document.querySelector(".navbar-light").clientHeight;
    var nav_position = nav.getBoundingClientRect();
    var left_position = nav_position.left;
    var top_position = nav_position.top;
    
    if (window.scrollY > crossed_div.clientHeight) {
        nav.classList.add("stuck");
    } else {
        nav.classList.remove("stuck");
        nav.style.top = main_nav + "px";
    }
}
    });
  }, []);

  return (
    <>
      <Head>
        <title>Technology 1 || Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SolutionBanner />
      <SimpleNav />
      <SolutionGoal />
      <HowWeWork hasTitle={true} />
      <Comments />
    </>
  );
}

export default Solutions;
